-- MySQL Script generated by MySQL Workbench
-- Tue Jul 23 16:51:40 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema appXudo
-- -----------------------------------------------------
-- Diagrama desañadp por Santiago Gutierrez CEO de XUDO.dev
DROP SCHEMA IF EXISTS `appXudo` ;

-- -----------------------------------------------------
-- Schema appXudo
--
-- Diagrama desañadp por Santiago Gutierrez CEO de XUDO.dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `appXudo` DEFAULT CHARACTER SET utf8 ;
USE `appXudo` ;

-- -----------------------------------------------------
-- Table `appXudo`.`md_callcenter_call_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appXudo`.`md_callcenter_call_status` (
  `id_call_status` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_call_status`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `appXudo`.`md_callcenter_campaign_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appXudo`.`md_callcenter_campaign_status` (
  `id_campaign_status` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_campaign_status`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `appXudo`.`md_callcenter_forms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appXudo`.`md_callcenter_forms` (
  `id_form` INT(11) NOT NULL AUTO_INCREMENT,
  `form` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_form`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `appXudo`.`md_callcenter_form_fields`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appXudo`.`md_callcenter_form_fields` (
  `id_form_field` INT(11) NOT NULL AUTO_INCREMENT,
  `id_form` INT(11) NULL DEFAULT NULL,
  `label` VARCHAR(100) NULL DEFAULT NULL,
  `value` VARCHAR(1000) NULL DEFAULT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_form_field`),
  INDEX `id_form` (`id_form` ASC),
  CONSTRAINT `md_callcenter_form_fields_ibfk_1`
    FOREIGN KEY (`id_form`)
    REFERENCES `appXudo`.`md_callcenter_forms` (`id_form`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `appXudo`.`md_callcenter_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appXudo`.`md_callcenter_schedule` (
  `id_schedule` INT(11) NOT NULL AUTO_INCREMENT,
  `id_call` INT(11) NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_schedule`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `appXudo`.`md_callcenter_scripts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appXudo`.`md_callcenter_scripts` (
  `id_script` INT(11) NOT NULL AUTO_INCREMENT,
  `script` VARCHAR(255) NULL DEFAULT NULL,
  `descripcion` VARCHAR(500) NULL DEFAULT NULL,
  `contenido_script` VARCHAR(10000) NULL DEFAULT NULL,
  PRIMARY KEY (`id_script`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `appXudo`.`md_callcenter_campaigns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appXudo`.`md_callcenter_campaigns` (
  `id_campaign` INT(11) NOT NULL AUTO_INCREMENT,
  `campaign` VARCHAR(255) NULL DEFAULT NULL,
  `id_form` INT(11) NULL DEFAULT NULL,
  `id_script` INT(11) NULL DEFAULT NULL,
  `id_campaign_status` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_campaign`),
  INDEX `id_form` (`id_form` ASC),
  INDEX `id_script` (`id_script` ASC),
  INDEX `id_campaign_status` (`id_campaign_status` ASC),
  CONSTRAINT `md_callcenter_campaigns_ibfk_3`
    FOREIGN KEY (`id_campaign_status`)
    REFERENCES `appXudo`.`md_callcenter_campaign_status` (`id_campaign_status`),
  CONSTRAINT `md_callcenter_campaigns_ibfk_1`
    FOREIGN KEY (`id_form`)
    REFERENCES `appXudo`.`md_callcenter_forms` (`id_form`)
    ON DELETE SET NULL,
  CONSTRAINT `md_callcenter_campaigns_ibfk_2`
    FOREIGN KEY (`id_script`)
    REFERENCES `appXudo`.`md_callcenter_scripts` (`id_script`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `appXudo`.`md_callcenter_settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appXudo`.`md_callcenter_settings` (
  `id_setting` INT(11) NOT NULL AUTO_INCREMENT,
  `campo` VARCHAR(255) NULL DEFAULT NULL,
  `value` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_setting`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `appXudo`.`md_genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appXudo`.`md_genero` (
  `id_genero` INT(11) NOT NULL AUTO_INCREMENT,
  `genero` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id_genero`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `appXudo`.`md_lvlformacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appXudo`.`md_lvlformacion` (
  `id_lvlformacion` INT(11) NOT NULL AUTO_INCREMENT,
  `formacion` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_lvlformacion`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `appXudo`.`md_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appXudo`.`md_menu` (
  `id_menu` INT(11) NOT NULL AUTO_INCREMENT,
  `menu` VARCHAR(50) NULL DEFAULT NULL,
  `icono` VARCHAR(25) NULL DEFAULT NULL,
  `url` VARCHAR(150) NULL DEFAULT '',
  `nivel_up` INT(11) NULL DEFAULT '0',
  `id_permiso` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_menu`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `appXudo`.`md_permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appXudo`.`md_permisos` (
  `id_permiso` INT(11) NOT NULL AUTO_INCREMENT,
  `perfil` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`id_permiso`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `appXudo`.`md_statuscivil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appXudo`.`md_statuscivil` (
  `id_statuscivil` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_statuscivil`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `appXudo`.`md_statususer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appXudo`.`md_statususer` (
  `id_statususer` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`id_statususer`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `appXudo`.`md_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appXudo`.`md_user` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(100) NULL DEFAULT NULL,
  `dni` VARCHAR(11) NOT NULL DEFAULT '',
  `id_genero` INT(11) NULL DEFAULT NULL,
  `pass` VARCHAR(500) NULL DEFAULT NULL,
  `id_permiso` INT(11) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `tel` VARCHAR(11) NULL DEFAULT NULL,
  `fec_nac` DATE NULL DEFAULT NULL,
  `id_lvlformacion` INT(11) NULL DEFAULT NULL,
  `id_statuscivil` INT(11) NULL DEFAULT NULL,
  `address` VARCHAR(500) NULL DEFAULT NULL,
  `fec_ingreso` DATETIME NULL DEFAULT NULL,
  `id_statususer` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_user`, `dni`),
  INDEX `id_permisos` (`id_permiso` ASC),
  INDEX `id_statuscivil` (`id_statuscivil` ASC),
  INDEX `id_genero` (`id_genero` ASC),
  INDEX `id_statususer` (`id_statususer` ASC),
  INDEX `md_user_ibfk_7_idx` (`id_lvlformacion` ASC),
  CONSTRAINT `md_user_ibfk_1`
    FOREIGN KEY (`id_permiso`)
    REFERENCES `appXudo`.`md_permisos` (`id_permiso`),
  CONSTRAINT `md_user_ibfk_2`
    FOREIGN KEY (`id_statuscivil`)
    REFERENCES `appXudo`.`md_statuscivil` (`id_statuscivil`),
  CONSTRAINT `md_user_ibfk_5`
    FOREIGN KEY (`id_genero`)
    REFERENCES `appXudo`.`md_genero` (`id_genero`),
  CONSTRAINT `md_user_ibfk_6`
    FOREIGN KEY (`id_statususer`)
    REFERENCES `appXudo`.`md_statususer` (`id_statususer`),
  CONSTRAINT `md_user_ibfk_7`
    FOREIGN KEY (`id_lvlformacion`)
    REFERENCES `appXudo`.`md_lvlformacion` (`id_lvlformacion`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `appXudo`.`md_grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appXudo`.`md_grupos` (
  `id_grupo` INT(11) NOT NULL AUTO_INCREMENT,
  `grupo` VARCHAR(255) NULL DEFAULT NULL,
  `id_user` INT(11) NULL DEFAULT NULL,
  `belong_user_grupo` VARCHAR(1000) NULL DEFAULT '[]',
  PRIMARY KEY (`id_grupo`),
  INDEX `id_user` (`id_user` ASC),
  CONSTRAINT `md_grupos_ibfk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `appXudo`.`md_user` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `appXudo`.`md_callcenter_calls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appXudo`.`md_callcenter_calls` (
  `id_call` INT(11) NOT NULL AUTO_INCREMENT,
  `id_campaign` INT(11) NULL DEFAULT NULL,
  `id_user` INT(11) NULL DEFAULT NULL,
  `phones` VARCHAR(50) NULL DEFAULT NULL,
  `nombres` VARCHAR(255) NULL DEFAULT NULL,
  `id_call_status` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_call`),
  INDEX `id_call_status` (`id_call_status` ASC),
  INDEX `id_user` (`id_user` ASC),
  INDEX `md_callcenter_calls_ibfk_3` (`id_campaign` ASC),
  CONSTRAINT `md_callcenter_calls_ibfk_3`
    FOREIGN KEY (`id_campaign`)
    REFERENCES `appXudo`.`md_callcenter_campaigns` (`id_campaign`)
    ON DELETE CASCADE,
  CONSTRAINT `md_callcenter_calls_ibfk_2`
    FOREIGN KEY (`id_call_status`)
    REFERENCES `appXudo`.`md_callcenter_call_status` (`id_call_status`),
  CONSTRAINT `md_callcenter_calls_ibfk_4`
    FOREIGN KEY (`id_user`)
    REFERENCES `appXudo`.`md_user` (`id_user`)
    ON DELETE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `appXudo`.`md_callcenter_call_registry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appXudo`.`md_callcenter_call_registry` (
  `id_call_registry` INT(11) NOT NULL AUTO_INCREMENT,
  `id_call` INT(11) NULL DEFAULT NULL,
  `id_call_status` INT(11) NULL DEFAULT NULL,
  `dst` VARCHAR(80) NULL DEFAULT NULL,
  `calldate` DATETIME NULL DEFAULT NULL,
  `uniqueid` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`id_call_registry`),
  INDEX `id_call` (`id_call` ASC),
  INDEX `id_call_status` (`id_call_status` ASC),
  CONSTRAINT `md_callcenter_call_registry_ibfk_2`
    FOREIGN KEY (`id_call_status`)
    REFERENCES `appXudo`.`md_callcenter_call_status` (`id_call_status`),
  CONSTRAINT `md_callcenter_call_registry_ibfk_1`
    FOREIGN KEY (`id_call`)
    REFERENCES `appXudo`.`md_callcenter_calls` (`id_call`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `appXudo`.`md_callcenter_form_data_recolected`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appXudo`.`md_callcenter_form_data_recolected` (
  `id_form_data_recolected` INT(11) NOT NULL AUTO_INCREMENT,
  `id_call_registry` INT(11) NULL DEFAULT NULL,
  `id_form` INT(11) NULL DEFAULT NULL,
  `data` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`id_form_data_recolected`),
  INDEX `id_call_registry` (`id_call_registry` ASC),
  INDEX `id_form` (`id_form` ASC),
  CONSTRAINT `md_callcenter_form_data_recolected_ibfk_2`
    FOREIGN KEY (`id_form`)
    REFERENCES `appXudo`.`md_callcenter_forms` (`id_form`)
    ON DELETE NO ACTION,
  CONSTRAINT `md_callcenter_form_data_recolected_ibfk_1`
    FOREIGN KEY (`id_call_registry`)
    REFERENCES `appXudo`.`md_callcenter_call_registry` (`id_call_registry`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `appXudo`.`md_callcenter_call_attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appXudo`.`md_callcenter_call_attribute` (
  `id_call_attribute` INT(11) NOT NULL AUTO_INCREMENT,
  `id_call` INT(11) NULL DEFAULT NULL,
  `data_attribute` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`id_call_attribute`),
  INDEX `id_call` (`id_call` ASC),
  CONSTRAINT `md_callcenter_call_attribute_ibfk_1`
    FOREIGN KEY (`id_call`)
    REFERENCES `appXudo`.`md_callcenter_calls` (`id_call`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `appXudo`.`md_users_grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appXudo`.`md_users_grupos` (
  `id_grupo` INT(11) NULL DEFAULT NULL,
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_user`),
  INDEX `id_grupo` (`id_grupo` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `appXudo` ;

-- -----------------------------------------------------
-- Placeholder table for view `appXudo`.`registro_llamadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appXudo`.`registro_llamadas` (`id_call_registry` INT, `id_campaign` INT, `campaign` INT, `'nombres cliente'` INT, `'hora llamada'` INT, `'número llamado'` INT, `phones` INT, `'duración'` INT, `estado` INT, `'resultado'` INT, `'extensión'` INT, `'Agente'` INT, `'cdr_uniqueid'` INT, `'cdr_recordingfile'` INT, `'data formulario'` INT);

-- -----------------------------------------------------
-- View `appXudo`.`registro_llamadas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appXudo`.`registro_llamadas`;
USE `appXudo`;
CREATE
   OR REPLACE ALGORITHM = UNDEFINED
  VIEW `registro_llamadas`
  AS
  SELECT
    `a`.`id_call_registry`,
    `d`.`id_campaign`,
    `d`.`campaign`,
    `b`.`nombres` AS 'nombres cliente',
    `a`.`calldate` AS 'hora llamada',
    `z`.`dst` AS 'número llamado',
    `b`.`phones`,
    `z`.`billsec` AS 'duración',
    `e`.`estado`,
    `z`.`disposition` AS 'resultado',
    `z`.`src` AS 'extensión',
    `f`.`nombres` AS 'Agente',
    `z`.`uniqueid` AS 'cdr_uniqueid',
    `z`.`recordingfile` AS 'cdr_recordingfile',
    `c`.`data` AS 'data formulario'
  FROM
    ((((((`md_callcenter_call_registry` a
      LEFT JOIN `md_callcenter_calls` b ON ((`a`.`id_call` = `b`.`id_call`)))
      LEFT JOIN `md_callcenter_form_data_recolected` c ON ((`a`.`id_call_registry` = `c`.`id_call_registry`)))
      LEFT JOIN `md_callcenter_campaigns` d ON ((`b`.`id_campaign` = `d`.`id_campaign`)))
      LEFT JOIN `md_callcenter_call_status` e ON ((`a`.`id_call_status` = `e`.`id_call_status`)))
      LEFT JOIN `md_user` f ON ((`b`.`id_user` = `f`.`id_user`)))
      LEFT JOIN `asteriskcdrdb`.`cdr` z ON ((`a`.`uniqueid` = CONVERT(`z`.`uniqueid` USING utf8))))
  ORDER BY `a`.`id_call_registry`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `appXudo`.`md_callcenter_call_status`
-- -----------------------------------------------------
START TRANSACTION;
USE `appXudo`;
INSERT INTO `appXudo`.`md_callcenter_call_status` (`id_call_status`, `estado`) VALUES (1, 'sin llamar');
INSERT INTO `appXudo`.`md_callcenter_call_status` (`id_call_status`, `estado`) VALUES (2, 'contactado');
INSERT INTO `appXudo`.`md_callcenter_call_status` (`id_call_status`, `estado`) VALUES (3, 'no contesta');
INSERT INTO `appXudo`.`md_callcenter_call_status` (`id_call_status`, `estado`) VALUES (4, 'llamar despues');

COMMIT;


-- -----------------------------------------------------
-- Data for table `appXudo`.`md_callcenter_campaign_status`
-- -----------------------------------------------------
START TRANSACTION;
USE `appXudo`;
INSERT INTO `appXudo`.`md_callcenter_campaign_status` (`id_campaign_status`, `estado`) VALUES (1, 'activa');
INSERT INTO `appXudo`.`md_callcenter_campaign_status` (`id_campaign_status`, `estado`) VALUES (2, 'inactiva');

COMMIT;


-- -----------------------------------------------------
-- Data for table `appXudo`.`md_genero`
-- -----------------------------------------------------
START TRANSACTION;
USE `appXudo`;
INSERT INTO `appXudo`.`md_genero` (`id_genero`, `genero`) VALUES (1, 'Masculino');
INSERT INTO `appXudo`.`md_genero` (`id_genero`, `genero`) VALUES (2, 'Femenino');

COMMIT;


-- -----------------------------------------------------
-- Data for table `appXudo`.`md_lvlformacion`
-- -----------------------------------------------------
START TRANSACTION;
USE `appXudo`;
INSERT INTO `appXudo`.`md_lvlformacion` (`id_lvlformacion`, `formacion`) VALUES (1, 'Primaria');
INSERT INTO `appXudo`.`md_lvlformacion` (`id_lvlformacion`, `formacion`) VALUES (2, 'Secundaria');
INSERT INTO `appXudo`.`md_lvlformacion` (`id_lvlformacion`, `formacion`) VALUES (3, 'Superior 1mer Nivel');

COMMIT;


-- -----------------------------------------------------
-- Data for table `appXudo`.`md_menu`
-- -----------------------------------------------------
START TRANSACTION;
USE `appXudo`;
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (1, 'dashboard', 'ti-dashboard', '', 0, '{1,2,3,4}');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (2, 'panel administrador', '', 'dashboard', 1, '{1,2}');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (4, 'sistema', 'ti-layout-sidebar-left', '', 0, '{1}');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (8, 'clientes', 'ti-id-badge', '', 0, '{}');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (9, 'todos los clientes', '', 'clientes', 8, '{}');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (10, 'usuarios', 'ti-user', '', 0, '{1}');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (11, 'todos los usuarios', '', 'usuarios', 10, '{1}');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (12, 'historias clinicas', 'ti-bookmark-alt', '', 0, '');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (13, 'todas las historias', '', 'historiasclinicas', 12, '');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (14, 'añadir nueva', '', 'historiasclinicas/historia', 12, '');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (15, 'workflows', 'ti-bolt', '', 0, '{}');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (16, 'tareas', '', 'workflows', 15, '{}');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (17, 'añadir nuevo', '', 'clientes/cliente', 8, '{}');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (18, 'añadir nuevo', '', 'usuarios/usuario', 10, '{1}');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (19, 'añadir nueva', '', 'workflows/workflow', 15, '{}');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (20, 'tienda', 'ti-shopping-cart', '', 0, '{}');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (21, 'todas las ventas', '', 'tienda/ventas', 20, '{}');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (22, 'productos', '', 'tienda/productos', 20, '{}');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (23, 'pagos', '', 'tienda/pagos', 20, '{}');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (24, 'callcenter', 'ti-headphone-alt', '', 0, '{1,2}');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (25, 'grupos', '', 'usuarios/grupos', 10, '{1}');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (26, 'configuración', '', '', 4, '{1}');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (27, 'gestionar', '', 'callcenter/calls', 24, '{1,2}');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (28, 'campañas', '', 'callcenter/campaigns', 24, '{1}');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (29, 'formularios', '', 'callcenter/forms', 24, '{1}');
INSERT INTO `appXudo`.`md_menu` (`id_menu`, `menu`, `icono`, `url`, `nivel_up`, `id_permiso`) VALUES (30, 'guiones', '', 'callcenter/scripts', 24, '{1}');

COMMIT;


-- -----------------------------------------------------
-- Data for table `appXudo`.`md_permisos`
-- -----------------------------------------------------
START TRANSACTION;
USE `appXudo`;
INSERT INTO `appXudo`.`md_permisos` (`id_permiso`, `perfil`) VALUES (1, 'Administrador');
INSERT INTO `appXudo`.`md_permisos` (`id_permiso`, `perfil`) VALUES (2, 'Vendedor');
INSERT INTO `appXudo`.`md_permisos` (`id_permiso`, `perfil`) VALUES (3, 'Director');
INSERT INTO `appXudo`.`md_permisos` (`id_permiso`, `perfil`) VALUES (4, 'Autorizador');
INSERT INTO `appXudo`.`md_permisos` (`id_permiso`, `perfil`) VALUES (5, 'Contador');

COMMIT;


-- -----------------------------------------------------
-- Data for table `appXudo`.`md_statuscivil`
-- -----------------------------------------------------
START TRANSACTION;
USE `appXudo`;
INSERT INTO `appXudo`.`md_statuscivil` (`id_statuscivil`, `estado`) VALUES (1, 'Soltero');
INSERT INTO `appXudo`.`md_statuscivil` (`id_statuscivil`, `estado`) VALUES (2, 'Casado');
INSERT INTO `appXudo`.`md_statuscivil` (`id_statuscivil`, `estado`) VALUES (3, 'Divorsiado');
INSERT INTO `appXudo`.`md_statuscivil` (`id_statuscivil`, `estado`) VALUES (4, 'Union libre');

COMMIT;


-- -----------------------------------------------------
-- Data for table `appXudo`.`md_statususer`
-- -----------------------------------------------------
START TRANSACTION;
USE `appXudo`;
INSERT INTO `appXudo`.`md_statususer` (`id_statususer`, `estado`) VALUES (1, 'habilitado');
INSERT INTO `appXudo`.`md_statususer` (`id_statususer`, `estado`) VALUES (2, 'deshabilitado');

COMMIT;


-- -----------------------------------------------------
-- Data for table `appXudo`.`md_user`
-- -----------------------------------------------------
START TRANSACTION;
USE `appXudo`;
INSERT INTO `appXudo`.`md_user` (`id_user`, `nombres`, `dni`, `id_genero`, `pass`, `id_permiso`, `email`, `tel`, `fec_nac`, `id_lvlformacion`, `id_statuscivil`, `address`, `fec_ingreso`, `id_statususer`) VALUES (1, 'Aministrador', '1756666598', 1, 'U2wpZq1+FzTxJ2eaOZSI+XE7+4XQOq3kUqnVInjkmxeC71msZ00cUEF7ajVn5w/N3OOgmDs4uwoeB9x2OgZK9g==', 1, 'zam.2014.sg@gmail.com', '0984904911', '1997-11-07', 3, 2, 'Pedro Ponce Carrasco Oe-06 y Av. Diego de almagro', '', 1);

COMMIT;

